name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: ./backend

env:
  ECR_REPOSITORY: udacity-devops

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: '3.10'
        cache: 'pipenv'
    - run: echo '${{ steps.setup_python.outputs.cache-hit }}' # true if cache-hit occurred on the primary key

    - name: Install pipenv
      run: pip install pipenv

    # - name: Cache Pipenv dependencies
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.local/share/virtualenvs
    #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pipenv-

    - name: Install Dependencies
      # run: pipenv install --system --deploy
      run: pipenv install --deploy

    - name: Lint
      run: pipenv run lint

    - name: Test
      run: pipenv run test

    - name: Build Docker image
      run: docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
