name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/actions/backend/**'
      - '.github/workflows/backend*'
  workflow_dispatch:
  workflow_call:

env:
  ECR_REPOSITORY: backend

defaults:
  run:
    working-directory: ./backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          backend

    - name: Setup backend
      uses: ./.github/actions/backend

    - name: Lint
      run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          backend

    - name: Setup backend
      uses: ./.github/actions/backend

    - name: Test
      run: pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          backend

    - name: Setup backend
      uses: ./.github/actions/backend

    - name: Build Docker image
      run: docker build -t ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
